extends: airbnb
installedESLint: true
plugins:
  - react
  - babel
rules:
  no-console: 0
  no-param-reassign: 0
  semi: [2, "never"]
  new-cap: ["error", { "capIsNewExceptions": ["Map", "DragDropContext", "DragSource", "DropTarget"] }]
  radix: ["error", "as-needed"]
  # generator-star-spacing: 0
  # babel/generator-star-spacing: 1
  # babel/new-cap: 1
  # babel/array-bracket-spacing: 1
  # babel/object-curly-spacing: 1
  # babel/object-shorthand: 1
  # babel/arrow-parens: 1
  # babel/no-await-in-loop: 1
  # babel/flow-object-type: 1
  # babel/func-params-comma-dangle: 1

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
      jsx: true
      experimentalObjectRestSpread: true
