extends: airbnb
installedESLint: true
plugins:
  - react
rules:
  no-console: 0
  no-param-reassign: 0
  semi: [2, "never"]

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
      jsx: true
      experimentalObjectRestSpread: true
