extends: airbnb
installedESLint: true
plugins:
  - react
  - babel
rules:
  no-console: 0
  no-param-reassign: 0
  semi: [2, "never"]
  new-cap: ["error", { "capIsNewExceptions": ["Map", "DragDropContext", "DragSource", "DropTarget"] }]
  radix: ["error", "as-needed"]

parser: babel-eslint

globals:
  fetch: true
  Headers: true

parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
      jsx: true
      experimentalObjectRestSpread: true
